package io.github.tuanhiep.ltsjavalab.verification;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Arrays;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import org.junit.jupiter.api.Test;

class SchemaAndPoolingPostgresIT extends PostgresContainerBase {

    @Test
    void additiveMigrationAndJdbcBatchRunOnTheRealEngine() throws Exception {
        try (var connection = DriverManager.getConnection(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
             var statement = connection.createStatement()) {
            statement.execute("drop table if exists users");
            statement.execute("""
                    create table users (
                        id bigint generated by default as identity primary key,
                        email_legacy varchar(320) not null
                    )
                    """);
            statement.execute("alter table users add column email_normalized varchar(320)");

            try (var insert = connection.prepareStatement(
                    "insert into users(email_legacy) values (?)")) {
                for (int index = 0; index < 100; index++) {
                    insert.setString(1, "USER" + index + "@EXAMPLE.COM");
                    insert.addBatch();
                }
                assertThat(Arrays.stream(insert.executeBatch()).sum()).isEqualTo(100);
            }

            try (var backfill = connection.prepareStatement("""
                    update users
                       set email_normalized = lower(email_legacy)
                     where id = ?
                    """)) {
                for (long id = 1; id <= 100; id++) {
                    backfill.setLong(1, id);
                    backfill.addBatch();
                }
                assertThat(Arrays.stream(backfill.executeBatch()).sum()).isEqualTo(100);
            }

            try (var result = statement.executeQuery(
                    "select count(*) from users where email_normalized is not null")) {
                assertThat(result.next()).isTrue();
                assertThat(result.getInt(1)).isEqualTo(100);
            }

            statement.execute("alter table users drop column email_legacy");
            assertThatThrownBySql(() -> statement.executeQuery(
                    "select email_legacy from users"));
        }
    }

    @Test
    void poolLimitIsAnExplicitAdmissionBoundary() throws Exception {
        var config = new HikariConfig();
        config.setJdbcUrl(POSTGRES.getJdbcUrl());
        config.setUsername(POSTGRES.getUsername());
        config.setPassword(POSTGRES.getPassword());
        config.setMaximumPoolSize(4);
        config.setMinimumIdle(1);
        config.setConnectionTimeout(3_000);

        try (var dataSource = new HikariDataSource(config);
             var connection = dataSource.getConnection()) {
            assertThat(dataSource.getMaximumPoolSize()).isEqualTo(4);
            assertThat(connection.isValid(2)).isTrue();
        }
    }

    private static void assertThatThrownBySql(SqlOperation operation) {
        try {
            operation.run();
            throw new AssertionError("expected PostgreSQL to reject the dropped column");
        } catch (SQLException expected) {
            assertThat(expected.getSQLState()).isEqualTo("42703");
        }
    }

    @FunctionalInterface
    private interface SqlOperation {
        void run() throws SQLException;
    }
}
